[project]
name = "django-modern-schemas"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Izcar J. Munoz Torrez", email = "izcarmt95+gitlab.com@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "django>=3.2",
    "pydantic[email,timezone]>=2.13.4",
    "pyrefly>=1.2.0",
    "ruff>=0.16.0",
    "ty>=0.0.63",
]
tests = [
    "django-stubs>=6.0.7",
    "pytest>=9.1.1",
    "pytest-cov>=6.0",
    "pytest-django>=4.12.0",
]
docs = [
    "mkdocs-material>=9.7.0",
]
[tool.ruff]
src=["src"]
exclude = ["migrations"]
line-length = 120

[tool.ruff.lint]
fixable = ["F401", "E501", "ALL"]
unfixable = []
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade,
  "I",   # isort
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 120
