"""Makes every ``>>>`` example in the documentation an executed test.

The guides are collected by pytest via ``--doctest-glob=*.md``. Each page runs
against the example Django app in ``examples/models.py`` with a real (in-memory)
database, so the outputs printed in the docs are the outputs the library
actually produces. A drifting example fails the build.
"""

import pytest


@pytest.fixture(autouse=True)
def _isolate_schema_registry():
    """Give each page a clean schema registry.

    ``SchemaRegister`` is a Borg — every instance shares one dict — so a schema
    generated by another page (or by the unit tests) would otherwise be returned
    from the cache here, making the pages order-dependent.
    """
    from django_modern_schemas.orm.schema_registry import registry

    saved_schemas = dict(registry.schemas)
    saved_fields = dict(registry.fields)
    registry.schemas.clear()
    registry.fields.clear()
    try:
        yield
    finally:
        registry.schemas.clear()
        registry.schemas.update(saved_schemas)
        registry.fields.clear()
        registry.fields.update(saved_fields)


@pytest.fixture(autouse=True)
def _documentation_namespace(request, doctest_namespace, db):
    """Preload the names every guide uses and give doctests database access."""
    if request.node.__class__.__name__ != 'DoctestItem':  # pragma: no cover - non-doctest collection
        return

    import json
    from typing import Annotated
    from uuid import uuid4

    from examples import models

    from django_modern_schemas import (
        MethodSource,
        ModelSchema,
        Schema,
        SchemaFactory,
        Source,
        SourceResolutionError,
        SourceResolver,
    )

    doctest_namespace.update(
        Annotated=Annotated,
        json=json,
        models=models,
        MethodSource=MethodSource,
        ModelSchema=ModelSchema,
        Schema=Schema,
        SchemaFactory=SchemaFactory,
        Source=Source,
        SourceResolutionError=SourceResolutionError,
        SourceResolver=SourceResolver,
        uuid4=uuid4,
    )
